import{a as P,S as m,i as n}from"./assets/vendor-BgmC94F3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const f=15;async function p(r,t=1){const i={key:"52994233-7ffb60f08ba14b4da4bef7a73",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f};return(await P.get("https://pixabay.com/api/",{params:i})).data}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".bttn-more");let l=new m(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:a,comments:q,downloads:E})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img class="gallery-image" src="${i}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${a}</p>
          <p class="info-item"><b>Comments</b> ${q}</p>
          <p class="info-item"><b>Downloads</b> ${E}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),l.refresh()}function R(){h.innerHTML="",l.destroy(),l=new m(".gallery a",{captionsData:"alt",captionDelay:250})}function L(){g.classList.add("is-visible")}function v(){g.classList.remove("is-visible")}function w(){y.classList.remove("hidden")}function S(){y.classList.add("hidden")}const M=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]');let u="",c=1,d=0;M.addEventListener("submit",D);document.querySelector(".bttn-more").addEventListener("click",O);async function D(r){r.preventDefault();const t=$.value.trim();if(!t){n.warning({title:"Warning",message:"Search input must not be empty!",position:"topRight"});return}u=t,c=1,R(),S(),L();try{const i=await p(u,c);if(d=i.totalHits,!i.hits.length){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(b(i.hits),d<=f){n.info({title:"End of collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}w()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v()}}async function O(){S(),L(),c+=1;try{const r=await p(u,c);b(r.hits),x();const t=Math.ceil(d/f);c>=t?n.info({title:"End of collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w()}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{v()}}function x(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
