import{a as P,S as p,i as c}from"./assets/vendor-BgmC94F3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const u=10;async function g(o,t=1){const i={key:"52994233-7ffb60f08ba14b4da4bef7a73",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:u};return(await P.get("https://pixabay.com/api/",{params:i})).data}const h=document.querySelector(".gallery"),y=document.querySelector(".loader");let m=new p(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const t=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:n,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img class="gallery-image" src="${i}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${n}</p>
          <p class="info-item"><b>Comments</b> ${S}</p>
          <p class="info-item"><b>Downloads</b> ${q}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),m.refresh()}function E(){h.innerHTML="",m.destroy(),m=new p(".gallery a",{captionsData:"alt",captionDelay:250})}function L(){y.classList.add("is-visible")}function v(){y.classList.remove("is-visible")}const w=document.querySelector(".form"),R=document.querySelector('input[name="search-text"]'),s=document.querySelector(".bttn-more");let f="",l=1,d=0;w.addEventListener("submit",$);s.addEventListener("click",D);async function $(o){o.preventDefault();const t=R.value.trim();if(!t){c.warning({title:"Warning",message:"Search input must not be empty!",position:"topRight"});return}f=t,l=1,E(),s.classList.add("hidden"),L();try{const i=await g(f,l);if(d=i.totalHits,!i.hits.length){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(i.hits),d>u&&s.classList.remove("hidden")}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v(),w.reset()}}async function D(){l+=1,L();try{const o=await g(f,l);b(o.hits),M();const t=Math.ceil(d/u);l>=t&&(s.classList.add("hidden"),c.info({title:"End of collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{v()}}function M(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}s.classList.add("hidden");d>u&&s.classList.remove("hidden");
//# sourceMappingURL=index.js.map
